In [1]:
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
from sklearn.metrics import confusion_matrix

In [2]:
train = pd.read_csv('drive/My Drive/Colab Notebooks/train.csv')
test = pd.read_csv('drive/My Drive/Colab Notebooks/test.csv')

In [3]:
x_train = train.drop('class', axis=1)
y_train = train['class']
x_test = test.drop('actual-class', axis=1)
x_test = x_test.drop('ID', axis=1)
y_test = test['actual-class']

In [15]:

model = KNeighborsClassifier(n_neighbors=3, metric='manhattan')
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
man_rec = metrics.recall_score(y_test, y_pred)
man_acc = metrics.accuracy_score(y_test, y_pred)
man_prec = metrics.precision_score(y_test, y_pred)
man_f1 = metrics.f1_score(y_test, y_pred)
pred_prob = model.predict_proba(x_test)

In [16]:
print(man_rec)
print(man_acc)
print(man_prec)
print(man_f1)
print(pred_prob)

1.0
1.0
1.0
1.0
[[0.         1.        ]
 [0.66666667 0.33333333]
 [1.         0.        ]
 [0.         1.        ]
 [1.         0.        ]
 [0.         1.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [0.         1.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [0.66666667 0.33333333]
 [0.         1.        ]
 [0.         1.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]]


In [13]:

model1 = KNeighborsClassifier(n_neighbors=3, weights='distance', metric='euclidean')
model1.fit(x_train, y_train)
euc_y_pred = model1.predict(x_test)
euc_rec = metrics.recall_score(y_test, euc_y_pred)
euc_acc = metrics.accuracy_score(y_test, euc_y_pred)
euc_prec = metrics.precision_score(y_test, euc_y_pred)
euc_f1 = metrics.f1_score(y_test, euc_y_pred)
pred_prob = model1.predict_proba(x_test)

In [14]:
print(euc_rec)
print(euc_acc)
print(euc_prec)
print(euc_f1)
print(pred_prob)

1.0
0.95
0.8571428571428571
0.923076923076923
[[0.         1.        ]
 [0.67384254 0.32615746]
 [1.         0.        ]
 [0.         1.        ]
 [1.         0.        ]
 [0.         1.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [0.         1.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [0.33961354 0.66038646]
 [0.         1.        ]
 [0.         1.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]]


In [10]:
print(y_pred)
print(euc_y_pred)

[1 0 0 1 0 1 0 0 0 0 1 0 0 0 0 1 1 0 0 0]
[1 0 0 1 0 1 0 0 0 0 1 0 0 0 1 1 1 0 0 0]


In [8]:
print('Model using Manhattan distance:')
confusion_matrix(y_test, y_pred)

Model using Manhattan distance:


array([[14,  0],
       [ 0,  6]])

In [9]:
print('Model using Euclidean distance:')
confusion_matrix(y_test, euc_y_pred)

Model using Euclidean distance:


array([[13,  1],
       [ 0,  6]])

Result: We find that the model using Manhattan distance performs better than the model using Euclidean distance.